### PR TITLE
Added cubemap support for React and react reference chaining glsl-pipeline feature.

### PR DESCRIPTION
**Pull request by ammein**
I added cubemap react support and a tiny feature could change the way of `GlslPipelineReact` render when I tried to replicate `devlook` in react. Here are some updates:
- I did conditional statement whenever the `React.Ref` has an instance of `GlslPipeline` in it, use it. Here is the code that I made in `glsl-pipeline-react.tsx`:
```ts
const pipeline = React.useMemo(() => {
        // Apply the same glsl if ref given the same glsl-pipeline reference
        let glsl: GlslPipelineClass;
        
        // Check if ref.current exists and instance of GlslPipeline class
        if (ref && (ref as React.RefObject<GlslPipelineClass>).current instanceof GlslPipeline) {

            // Assign to existing GlslPipeline
            glsl = (ref as React.RefObject<GlslPipelineClass>).current as GlslPipelineClass;
            
            // Apply uniforms if exists
            if(uniforms) {
                glsl.uniforms = uniforms;
            }

            // Apply options if any
            if(props) {
                glsl.options = props;
            }

        } else {
            // Else initialized new GlslPipeline
            glsl = new GlslPipeline(gl, uniforms, props);
        }
        

        glsl.load(fragmentShader, vertexShader);

        return glsl;
    }, [fragmentShader, vertexShader, gl, uniforms, props, ref]);
```

- Added `react_devlook` example along with Typescript supported.

---

I also did update the npmjs version using `changeset`. If you approved all these reviews and merged, could you please run the command here to publish to npmjs and push to Github as well? Simply run these
```bash
# Run Release script from root to publish package to npmjs
yarn release

# Push to Github for the latest updates
git push origin main
```

### CODE REVIEW

**Comment by ammein** [comment]
The package unfortunately relies on other major peerDependencies packages, therefore the package has been updated to `5.0.0` . A major change needed for this package to work.

**Comment by patriciogonzalezvivo** [comment]
Cool thank you! Question, is there a way to bump only the minor versioning? instead the mayor?
Let me know when you are finish and ready to test and merge

**Comment by patriciogonzalezvivo** [comment]
Q: you mean I merge here in github, then pull the changes locally and then run:

```
# Run Release script from root to publish package to npmjs
yarn release

# Push to Github for the latest updates
git push origin main
```

**Comment by ammein** [comment]
> Cool thank you! Question, is there a way to bump only the minor versioning? instead the mayor?
> 
> Let me know when you are finish and ready to test and merge

I believe it was issued by others as well on this:

https://github.com/atlassian/changesets/issues/555

Anyway, let me try change the version manually on my end and test before push to this PR to merge in Github 😊

**Comment by ammein** [comment]
> Q: you mean I merge here in github, then pull the changes locally and then run:
> 
> 
> 
> ```
> 
> # Run Release script from root to publish package to npmjs
> 
> yarn release
> 
> 
> 
> # Push to Github for the latest updates
> 
> git push origin main
> 
> ```

That is correct 👍🏼 I believe you're the owner of this package that can publish to the npmjs if I'm not mistaken 😊

**Comment by ammein** [comment]
All done! @patriciogonzalezvivo . The package has been updated to a minor version. All you need to do is these commands in your local when merged.

```bash
# Run Release script from root to publish package to npmjs
yarn release

# Push to Github for the latest updates
git push origin main
```

**Comment by ammein** [comment]
You're the best! Thank you! 🥳 @patriciogonzalezvivo

**Pull request merged**
