### PR TITLE
Adding setCubemap()

### PR DESCRIPTION
**Pull request by patriciogonzalezvivo**
@ammein I'm trying to add Cubemap support but running into multiple issues trying to `npm link` this to the project I'm working on. Also if I try to `yarn build` I get this: 

```bash
(base) [0.530s][1][main][~/Desktop/glsl-pipeline]$ yarn build
yarn run v1.22.22
$ preconstruct build
🎁 error Error: EACCES: permission denied, open '/home/patricio/Desktop/glsl-pipeline/package/r3f/dist/preconstruct-test-file'
🎁 info If you want to learn more about the above error, check https://preconstruct.tools/errors
🎁 info If the error is not there and you want to learn more about it, open an issue at https://github.com/preconstruct/preconstruct/issues/new
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Any help will be wellcome

### CODE REVIEW

**Comment by ammein** [comment]
@patriciogonzalezvivo  Hmm, have you tried install the package in your local `glsl-pipeline` by simply running:
```bash
yarn
```

If the error still produce the same output above, it seems that your folder has not gained permission access to that `dist` file. Perhaps you would try running this command in your shell:
```bash
chmod 777 /path/to/foldername
```

If all the above are successful, you may run `yarn build` again and see the outcome.

**Comment by patriciogonzalezvivo** [comment]
thank you @ammein! that certainly worked:

```bash
(base) [81ms][1][cubemap][~/Desktop/glsl-pipeline]$ sudo chmod -R 777 *
[sudo] password for patricio: 
(base) [2.949s][cubemap][~/Desktop/glsl-pipeline]$ yarn
yarn install v1.22.22
[1/4] Resolving packages...
success Already up-to-date.
$ preconstruct dev && manypkg check
🎁 info project is valid!
🎁 success created links!
☔️ success workspaces valid!
Done in 0.54s.
``` 

Thank you!

**Comment by ammein** [comment]
Awesome @patriciogonzalezvivo ! Glad to help! I can't wait to have this new feature that you are trying to build! Tag me if you need any help on typescript part for your new feature. I may be able contribute 👍🏼

P/s: It would be better if you provide one vanilla-js example on this cubemap feature for me to know what/how does the setup works 😅 Can't wait!

**Comment by patriciogonzalezvivo** [comment]
I'm adding support for Cubemaps.
If a scene is provided, a new light probe with Spherical Harmonics is created.

I'm also fixing an old issue where shadowmaps are not set because of raising states. Any change on defines now force a reload of the shaders (and shader materials)

**Comment by patriciogonzalezvivo** [comment]
@ammein I definitely will love your help and input for the TS end. I will add you as a reviewer and collaborator too.

I'm creating a new example here https://github.com/patriciogonzalezvivo/devlook that booth feature this WIP branch together with this WIP of lygia https://github.com/patriciogonzalezvivo/lygia/pull/231

**Comment by patriciogonzalezvivo** [comment]
https://github.com/user-attachments/assets/16f078a6-0441-45c2-90e5-bb1cdafce554

**Comment by ammein** [comment]
Updates:
- I've got it working on `vanilla-js` & `vanilla-ts` by modifying temporary lygia fixes. Currently working on react examples.
- Updates latest packages that shows error on typescript mismatched linting.

TODO:
- Provide complete example for devlook in react.

**Comment by patriciogonzalezvivo** [comment]
Fantastic! Thank you! there is no need to add the entire example to this repo. it will live and be improve on the other one. Probably there is a more simple way to just show case the cubemap and SH from the light probe.

**Comment by ammein** [comment]
Great! Just to be sure, if you want to publish the package soon, you'll follow this guideline yeah?

[For Owner Release Package](https://github.com/patriciogonzalezvivo/glsl-pipeline/blob/main/package/CONTRIBUTING.md#for-owner-wants-to-release-the-package)

**Comment by patriciogonzalezvivo** [comment]
Yes! I'm just waiting for your approval of the PR : )

**Review by ammein — APPROVED** [review]
Approved!

**Comment by ammein** [comment]
@patriciogonzalezvivo  I see that you pushed the npmjs package to new version `4.0.0` . Can push your local changes to github? I would like to continue work on provide support cubemap for React package.

**Comment by patriciogonzalezvivo** [comment]
@ammein pushed! sorry for that

**Comment by ammein** [comment]
No worries! @patriciogonzalezvivo

**Pull request merged**
