### PR TITLE
Hotfix: React "Render Main" Mesh Fix

### PR DESCRIPTION
**Pull request by ammein**
- Added new React examples for "Render Main"
- Fix "Render Main" ungenerated mesh on `billboard_scene` due to how the react code component structured using material as object attached. Provide conditional `primitive` component for specific type like this:
  ```tsx
    return (
        <>
            {
                type === 'scene' ? <primitive ref={ref} attach='material' object={material as THREE.ShaderMaterial} /> : type === 'main' &&
                <mesh>
                    <planeGeometry args={[2, 2]} />
                    <primitive ref={ref} attach='material' object={material as THREE.ShaderMaterial} />
                </mesh>
            }
        </>
    )
  ```
  
  > Once merged, please do this script from the root folder. This PR must be published on NPM for the 'Render Main' hotfix. I made it easy for you for every PR merge you need to publish from `maintainers`.
  ```bash
  yarn release
  ```

### CODE REVIEW

**Comment by patriciogonzalezvivo** [comment]
thank you!

**Comment by ammein** [comment]
> thank you!

You're welcome! Hope you are not having trouble publishing to npm package by simply running the command from root folder like this:

```bash
yarn release
```

> Let me know if you need more assistance 🥳

**Comment by patriciogonzalezvivo** [comment]
I need to bump the version first, right?

**Comment by ammein** [comment]
No need to bump it. I already bump the version and added 'changelog' description generated from `changeset` command. Simply build and publish by running the `yarn release` command. 😊👍🏻

**Comment by ammein** [comment]
I also rewritten instructions in `CONTRIBUTING.md` on how publishing rules works for `Owner` vs `Maintainers`. Hopefully this will be standard protocol for all contributors & maintainers whenever they want to release a new package to npmjs by submitting a PR.

**Comment by patriciogonzalezvivo** [comment]
Thank you!

**Pull request merged**
